security:
    encoders:
        AppBundle\Entity\User: sha512
        AppBundle\Entity\IdPUser:
            id: appbundle.sha512salted_encoder

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        idpuser_provider:
            entity:
                class: AppBundle:IdPUser
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: app_idp_idplist
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/easy_admin/, role: ROLE_SUPER_ADMIN }
