- repo: https://github.com/digitalpulp/pre-commit-php.git
  sha: 1.3.0
  hooks:
  - id: php-lint
  #- id: php-unit
  - id: php-cs
    files: \.(php)$
    args: [--standard=PSR1 -p]
  - id: php-cbf
    files: \.(php)$
    args: [--standard=PSR1 -p]
